### PR TITLE
Level storage mappings

### PR DESCRIPTION
**Pull request by TheGlitch76**
First commit is copypasta from what Notch copypasta'd, which is public domain.
Second commit is my own work. Some of the names are ehh (OldRegionComparable) but they work for now.

### CODE REVIEW

**Comment by TheGlitch76** [comment]
ohno, i'm going to have to cherry pick these commits out because of the squash merge.

**Comment by valoeghese** [comment]
what's the problem with the squash merge?

**Comment by TheGlitch76** [comment]
My branch has the actual commit but master has a squashed one instead, so it was conflicted and resolved in the merge commit above. Should be an easy fix in IDEA's git UI.

**Comment by valoeghese** [comment]
can I merge?

**Comment by valoeghese** [comment]
also while you're at it can you bump the build number to 6 in build.gradle

**Comment by TheGlitch76** [comment]
Sure

**Pull request merged**
