### PR TITLE
`Block36` -> `MovingPiston`

### PR DESCRIPTION
**Pull request by williambl**
`Block36` bad and worst in game
I look forward to the :bike::house:ing that this PR may or may not cause.

### CODE REVIEW

**Comment by williambl** [comment]
(On a serious note, I don't really mind `Block36` all that much, I just prefer more descriptive names)

**Comment by Devan-Kerman** [comment]
no block36 is a terrible name

**Comment by CoolMineman** [comment]
block36 best name

**Comment by Devan-Kerman** [comment]
nou

**Comment by CoolMineman** [comment]
Block36 needs to stay or the universe will explode k thx

**Comment by Devan-Kerman** [comment]
the universe will explode

**Comment by Devan-Kerman** [comment]
merge or slap

**Comment by CoolMineman** [comment]
You slap me I close

**Comment by Devan-Kerman** [comment]
👏 I'll fuckin do it again

**Comment by valoeghese** [comment]
I will poll this for 24 hours

**Comment by valoeghese** [comment]
nvm I can combine this with supercoder's pr

**Pull request merged**
